apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- release.yaml
- repository.yaml
configMapGenerator:
  - name: traefik-config
    files:
    - dynamic.yaml=files/dynamic.yaml
configurations:
  - kustomizeconfig.yaml